Ios js bridge
ammarahm-ed/nativescript-magic-spells pull request #15
Opened 2022-10-02 17:19 UTC by ammarahm-ed

2022-10-03 17:02 UTC, shirakaba requested changes
This is all I have time to review for tonight, unfortunately! I think I'll need a few more hours to review this, but the gist of it looks very good!

2022-10-03 17:02 UTC, shirakaba commented on packages/react-native/converter.ios.ts
> +export function promisify(module: RCTBridgeModule, methodName: string, argumentTypes: RNObjcSerialisableType[], args) {
```suggestion
export function promisify(module: RCTBridgeModule, methodName: string, argumentTypes: RNObjcSerialisableType[], args: unknown[]): Promise<unknown> {
```
We might be able to return better than `Promise<unknown>` using some generics based on `module` and `methodName`, but I'll have to come back and have a think about it. It would be possible if all the modules were registered onto a common interface (and any new modules augmented that interface). But as it might not be possible, I'm not going to call it a dealbreaker.

2022-10-03 17:11 UTC, ammarahm-ed commented on packages/react-native/converter.ios.ts
> +        nativeArguments.push(Utils.dataSerialize(data));
Haha i think Nathan told me about it on discord a few days ago. And it's only exposed in 8.3.0+

2022-10-03 17:13 UTC, ammarahm-ed commented on packages/react-native/converter.ios.ts
> +        if (!data) throw new Error(`Argument at index ${i} expects a nonnull Object value`);
We can figure it out as we test some modules and see how they behave with our implementation.

2022-10-03 17:20 UTC, ammarahm-ed commented on packages/react-native/converter.ios.ts
> +export function promisify(module: RCTBridgeModule, methodName: string, argumentTypes: RNObjcSerialisableType[], args) {
We probably don't need it as the end users will be using the existing JS layer written by the library creator and not NativeModules directly. Even in React Native, I haven't found any types directly on NativeModules.MyModule.function unless explicitly added by the library creator. Hope that makes sense.

2022-10-03 17:35 UTC, ammarahm-ed commented
I should probably never use the mobile app again to resolve changes. We can probably Squash this pull into one commit

2022-10-04 00:52 UTC, shirakaba requested changes
A quick bit of extra review before work. Still plan to do another pass after this!

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/core/EventEmitter/NativeEventEmitter.ts
> +  constructor(nativeModule: NativeModule) {
We don't seem to be doing anything with the backing property, so could reduce to this:
```suggestion
  constructor(public nativeModule: NativeModule) {
```

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/core/EventEmitter/NativeEventEmitter.ts
> +    }
Worth at least collapsing the if conditions, but perhaps also doing a falsy check instead of a strict null check.
```suggestion
    if (Platform.OS === 'ios' && !nativeModule) {
      throw new Error('`new NativeEventEmitter()` requires a non-null argument.');
    }
```
But do we even need the falsy/null check? Can we rely on TypeScript, or is this being called automatically under-the-hood?

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/core/EventEmitter/NativeEventEmitter.ts
> +    }
Together with the above patch that assigns `nativeModule` to `this.nativeModule` implicitly, we could reduce this to:
```suggestion
    if (typeof nativeModule?.addListener !== 'function') {
      console.warn('`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.');
    }
    if (typeof nativeModule?. removeListeners !== 'function') {
      console.warn('`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners ` method.');
    }
```
Once I understand how this is being used, I'd like to have a second pass at reviewing this part too, as generally we want to trust TypeScript as far as possible and avoid having to do type checks on construction args. The exception is when it's a bunch of dynamic stuff happening automatically that could bypass the checks (which this could well be).

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/core/EventEmitter/NativeEventEmitter.ts
> +    this._nativeModule?.addListener(eventType);
With the constructor change, this would then change to:
```suggestion
    this.nativeModule?.addListener(eventType);
```

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/core/EventEmitter/NativeEventEmitter.ts
> +    this._nativeModule?.removeListeners(1);
With the constructor change, this would then change to:
```suggestion
    this.nativeModule?.removeListeners(1);
```

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/core/EventEmitter/NativeEventEmitter.ts
> +    this._nativeModule?.removeListeners(this.listenerCount(eventType));
With the constructor change, this would then change to:
```suggestion
    this.nativeModule?.removeListeners(this.listenerCount(eventType));
```

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/core/EventEmitter/NativeEventEmitter.ts
> +          this._nativeModule?.removeListeners(1);
With the constructor change, this would then change to:
```suggestion
          this._nativeModule?.removeListeners(1);
```

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/core/EventEmitter/NativeEventEmitter.ts
> +          subscription = null;
I don't have time to think about it, but I suspect this cleanup isn't necessary in JS. I'll come back to it.

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/core/EventEmitter/NativeEventEmitter.ts
> + */
After reviewing this file for a bit, I just noticed that it was forked from a Facebook file, hence the flow comments and hence why they're not relying completely on TypeScript to catch falsy values.

I can re-review after comparing against the original file to minimise future upstream diffs, or I can continue reviewing it simply for what it is. Up to you!

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/index.ios.ts
> +  }
```suggestion
  module: RCTBridgeModule;
  _bridge: RCTBridge = getCurrentBridge();
  moduleMethods: TModuleMethodsType;
  objcMethodsNames: string[];

  constructor(public moduleName: string) {
    this.moduleMethods = NativeModuleMap[this.moduleName];
    this.wrapNativeMethods();
  }
```

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/index.ios.ts
> +  _bridge: RCTBridge;
If the `_` just means that this is intended to be private, we could declare it like this instead:
```suggestion
  private bridge: RCTBridge;
```

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/index.ios.ts
> +const NativemModuleMap = require('@ammarahm-ed/react-native-podspecs/platforms/ios/lib/modulemap.json') as TNativeModuleMap;
```suggestion
const NativeModuleMap = require('@ammarahm-ed/react-native-podspecs/platforms/ios/lib/modulemap.json') as TNativeModuleMap;
```

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/index.ios.ts
> +    for (const moduleName in NativemModuleMap) {
```suggestion
    for (const moduleName in NativeModuleMap) {
```

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/index.ios.ts
> +class NativeModulesConstructor {
I think we can rewrite this as a utility function that creates an object, as it's not actually using class functionality.

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/js-modules.ios.ts
> +  }
```suggestion
  private bridge: RCTBridge = getCurrentBridge();
  private modules: { [name: string]: any; } = {};
  constructor() {
    this.bridge.setJSModuleInvokerCallback(this.jsModuleInvoker);
  }
```

2022-10-04 00:52 UTC, shirakaba commented on packages/react-native/js-modules.ios.ts
> +  }
Removing the `_` from the private members.
I've also returned the value of the invoked JS module - might be relevant for functions that synchronously return a value.
```suggestion
  jsModuleInvoker(moduleName: string, methodName: string, args: NSArray<any>) {
    return this.modules[moduleName]?.[methodName]?.(...toJSValue(args));
  }

  registerJSModule(name: string, module: any) {
    this.modules[name] = module;
  }

  unregisterJSModule(name: string) {
    delete this.modules[name];
  }
```

2022-10-04 02:51 UTC, ammarahm-ed commented on packages/react-native/core/EventEmitter/NativeEventEmitter.ts
> +    }
I am not 100% sure if it's okay to remove this. As this is taken from React Native's repo, I will keep the check here for now at least.

2022-10-04 02:57 UTC, ammarahm-ed commented on packages/react-native/core/EventEmitter/NativeEventEmitter.ts
> +    }
We probably need these two checks as we are not sure if those two methods exist on a native module or not. And I think these need to be added to our `NativeModuleHolder` class too.

2022-10-04 03:02 UTC, ammarahm-ed commented on packages/react-native/core/EventEmitter/NativeEventEmitter.ts
> + */
I have converted it to typescript from flow. Rest of it is the same. I have removed some flow generics as I think for now I don't want to deal with this at this point & in ts it's a bit different.

2022-10-04 03:03 UTC, ammarahm-ed commented on packages/react-native/core/EventEmitter/NativeEventEmitter.ts
> +          subscription = null;
I am not 100% sure either. We can look into it's use once we get some modules tested that have event listeners.

2022-10-04 13:25 UTC, shirakaba requested changes
I haven't reached all the files yet, but here's another tidbit!

2022-10-07 13:15 UTC, shirakaba requested changes

2022-10-07 13:15 UTC, shirakaba commented on tools/demo/react-native/index.ts
> +import Auth0 from 'react-native-auth0';
Just leaving this review comment to remind us to drop mentions of `react-native-auth0` when we come to merge this PR.

Incidentally, I think TypeScript will forgive `require()` imports for lacking typings:

```suggestion
const Auth0 = require('react-native-auth0');
```

... but if you do apply this code suggestion, don't let GitHub mark this review comment as resolved, as it's reminding us to remove `react-native-auth0` 😅

2022-10-07 13:15 UTC, shirakaba commented on packages/react-native/platforms/ios/lib/ExtraModules/RCTLinkingManager.h
> +/*
Would it be okay if we refactored our libraries to line up with React Native's file structure properly, so we'd have `Libraries/Linking`, `Libraries/LinkingIOS`, and `React/Base`?

2022-10-07 17:15 UTC, ammarahm-ed commented on packages/react-native/platforms/ios/lib/ExtraModules/RCTLinkingManager.h
> +/*
Yes probably that would make sense.

2022-10-09 03:49 UTC, shirakaba commented on tools/demo/react-native/index.ts
> +import Auth0 from 'react-native-auth0';
Resolving this, as deintegrating `react-native-auth0` is firmly on our to-do list.

2022-10-09 03:49 UTC, shirakaba commented on packages/react-native/platforms/ios/lib/ExtraModules/RCTLinkingManager.h
> +/*
Done!

2022-10-28 16:25 UTC, shirakaba approved these changes
Approving as the scope has grown out of control and it’s easier just to get this merged into main and do smaller PRs from then on.

2022-10-28 16:28 UTC, merged