Implement ios bridge
ammarahm-ed/nativescript-magic-spells pull request #8
Opened 2022-09-18 06:24 UTC by ammarahm-ed

2022-09-19 03:27 UTC, shirakaba requested changes
Most of my comments are just about keeping whitespace consistency, but there are some important nil checks that I'd like to introduce. But as for the implementation itself, it's so minimal that there's not much to critique and it looks good; well done!

I do have a worry, however. A lot of this PR involves deletions of (probably) unneeded bridge code. And although we may not ever need the functionality and it just adds bloat, I am significantly worried that it actually increases our diff from upstream if we do delete this code. I ideally want to make the process of keeping up with upstream a quick copy-and-paste job, even if we think upstream is going to be a reasonably stable target. What do you think?

2022-09-19 03:27 UTC, shirakaba commented on packages/react-native/platforms/ios/lib/Base/RCTBridge.m
> +    return [self moduleForName:moduleName];
Whitespace.
```suggestion
- (id)moduleForName:(NSString *)moduleName lazilyLoadIfNecessary:(BOOL)lazilyLoad {    
  return [self moduleForName:moduleName];
```

2022-09-19 03:27 UTC, shirakaba commented on packages/react-native/platforms/ios/lib/Base/RCTBridge.m
> +    return [self moduleForName:moduleName];
Nil check and whitespace.
```suggestion
- (id) moduleForClass:(Class)moduleClass {
  NSString *moduleName = RCTBridgeModuleNameForClass(moduleClass);
  if(!moduleName) return nil;
  return [self moduleForName:moduleName];
```

2022-09-19 03:27 UTC, shirakaba commented on packages/react-native/platforms/ios/lib/Base/RCTBridge.m
> +        [_callableJSModules setBridge:self];
Whitespace.
```suggestion
-(instancetype)init {
  if (self = [super init]) {
    RCTCurrentBridgeInstance = self;
    nativeModules = [NSMutableDictionary new];
    moduleRegistry = [[RCTModuleRegistry alloc] init];
    [moduleRegistry setBridge:self];
    _callableJSModules = [[RCTCallableJSModules alloc] init];
    [_callableJSModules setBridge:self];
```

2022-09-19 03:27 UTC, shirakaba commented on packages/react-native/platforms/ios/lib/Base/RCTBridge.m
> +    return self;
Whitespace.
```suggestion
  return self;
```

2022-09-19 03:27 UTC, shirakaba commented on packages/react-native/platforms/ios/lib/Base/RCTBridge.m
> +    [self enqueueJSCall:module method:method args:args completion:NULL];
Whitespace.
```suggestion
  NSArray<NSString *> *ids = [moduleDotMethod componentsSeparatedByString:@"."];
  NSString *module = ids[0];
  NSString *method = ids[1];
  [self enqueueJSCall:module method:method args:args completion:NULL];
```

2022-09-19 03:27 UTC, shirakaba commented on packages/react-native/platforms/ios/lib/Base/RCTBridge.m
> +    }
Whitespace.
```suggestion
  if (JSModuleInvokerCallback)  {
    JSModuleInvokerCallback(module,method,args,completion);
  }
```

2022-09-19 03:27 UTC, shirakaba commented on packages/react-native/platforms/ios/lib/Base/RCTBridge.m
> +    //Most probably not needed by any modules.
Whitespace.
```suggestion
  // Most probably not needed by any modules.
```

2022-09-19 04:38 UTC, ammarahm-ed commented on packages/react-native/index.ios.ts
> +    return RCTBridgeModuleNameForClass(module.class()) || module.class().name;
The second one seems better. This will change in the upcoming days as we write the actual JS implementation.

2022-09-19 04:42 UTC, ammarahm-ed commented on packages/react-native/platforms/ios/lib/Base/RCTBridge+Private.h
> +RCT_EXTERN NSDictionary<NSString *, Class> *RCTGetModuleClasses(void);
Usually modules access other modules through the moduleRegistry which is available in each module itself. Only the bridge itself uses this method to load native modules properly. Anyone trying to get a module classes is probably doing something wrong since the modules need to load in a specific context through the `RCTModuleData` class.

I changed it to simplify querying modules when needed since our implementation differs a little in that we are lazily loading modules.

2022-09-19 04:49 UTC, ammarahm-ed commented
@shirakaba The few changes we have made to the bridge are quite rigorous therefore we might not be able to drop-in changes from upstream in the future. We will have to put those changes in manually. Which should be very minimal since we don't care about the deep layered changes, just what's in RCTBridge/RCTModuleData. So I think we are good.

2022-09-19 07:09 UTC, shirakaba commented
> The few changes we have made to the bridge are quite rigorous therefore we might not be able to drop-in changes from upstream in the future.

When I say drop-in, I do still accept a certain amount of manual comparison - just trying to reduce it from hundreds of lines to dozens.

But if it's limited to RCTBridge and RCTModuleData, it's manageable. I'll leave it up to you.

2022-09-19 07:50 UTC, ammarahm-ed commented
@shirakaba It's only two files, the rest is same as the original repo so if something changes in upstream, we should be able to add it without much hassle hopefully.

2022-09-19 08:16 UTC, shirakaba commented
Okay, happy to approve this after getting the whitespace consistent!

2022-09-19 13:51 UTC, ammarahm-ed commented
@shirakaba Will fix the whitespace issues in a single commit.

2022-09-19 14:09 UTC, ammarahm-ed commented
Hey, so I am trying to fix the formatting in xcode and it seems to not fix the formatting issues.. How did you fix the formatting issues above?

2022-09-20 04:01 UTC, ammarahm-ed commented
I could not fix it properly without adding .clang-format file from react-native repo.

2022-09-20 13:40 UTC, shirakaba approved these changes
> Hey, so I am trying to fix the formatting in xcode and it seems to not fix the formatting issues.. How did you fix the formatting issues above?
I did it manually in GitHub's plain text editor 🥲

> I could not fix it properly without adding .clang-format file from react-native repo.
Well done on finding that! That'll help loads!

Approved!

2022-09-20 14:32 UTC, merged